/**
 * Transpile utilities for contracts.
 *
 * Provides functions to:
 * - Convert contracts from YAML/TOML to JSON
 * - Generate TypeScript modules with full type inference
 * - Resolve all $include directives
 * - Output a single flattened file
 */

import { loadWithBase, loadWithBaseSync, type LoadedContracts } from "./loader.ts";
import { resolve } from "@std/path";

/**
 * Transpile options
 */
export interface TranspileOptions {
  /** Output path for the generated file */
  output?: string;
  /** Pretty print the output (for JSON) */
  pretty?: boolean;
  /** Output format: 'json' for data, 'ts' for TypeScript module with type inference */
  format?: "json" | "ts";
}

/**
 * Transpile result
 */
export interface TranspileResult {
  /** The loaded and resolved contracts */
  contracts: LoadedContracts;
  /** The output string (JSON or TypeScript) */
  content: string;
  /** The output file path (if written) */
  outputPath?: string;
  /** For backwards compatibility */
  json: string;
}

/**
 * Generate TypeScript module content from contracts.
 * The generated module exports contracts with `as const` for full type inference.
 */
function generateTypeScript(contracts: LoadedContracts): string {
  const lines: string[] = [
    "/**",
    " * Auto-generated contract definitions.",
    " * DO NOT EDIT - Generated by orchestrator/transpile.ts",
    " *",
    " * Use with json-schema-to-ts for full type inference:",
    " *   import { FromSchema } from 'json-schema-to-ts';",
    " *   type Response = FromSchema<typeof contracts[0]['response']>;",
    " */",
    "",
  ];

  // Only include base if it was explicitly specified in the contract file
  // This avoids leaking absolute file paths into generated output
  if (contracts.originalBase !== undefined) {
    lines.push(`export const base = ${JSON.stringify(contracts.originalBase)} as const;`);
    lines.push("");
  }

  lines.push("export const contracts = [");

  for (const contract of contracts.contracts) {
    lines.push("  {");
    lines.push(`    path: ${JSON.stringify(contract.path)},`);
    lines.push(`    method: ${JSON.stringify(contract.method)},`);
    lines.push(`    description: ${JSON.stringify(contract.description)},`);
    lines.push(`    module: ${JSON.stringify(contract.module)},`);
    if (contract.request) {
      lines.push(`    request: ${JSON.stringify(contract.request, null, 2).split("\n").join("\n    ")},`);
    }
    lines.push(`    response: ${JSON.stringify(contract.response, null, 2).split("\n").join("\n    ")},`);
    if (contract.error) {
      lines.push(`    error: ${JSON.stringify(contract.error, null, 2).split("\n").join("\n    ")},`);
    }
    lines.push("  } as const,");
  }

  lines.push("] as const;");
  lines.push("");
  lines.push("export type Contracts = typeof contracts;");
  lines.push("export type Contract = Contracts[number];");
  lines.push("");

  return lines.join("\n");
}

/**
 * Transpile contracts from a source file.
 *
 * This function:
 * 1. Loads contracts from the source file (YAML, TOML, or JSON)
 * 2. Resolves all $include directives
 * 3. Outputs a flattened file (JSON or TypeScript)
 *
 * When format is 'ts', generates a TypeScript module with `as const` assertions
 * for full type inference with `json-schema-to-ts`.
 *
 * @param sourcePath - Path to the source contract file
 * @param options - Transpile options
 * @returns Transpile result with contracts and output content
 */
export async function transpile(
  sourcePath: string,
  options: TranspileOptions = {}
): Promise<TranspileResult> {
  const { output, pretty = true, format = "json" } = options;

  // Load and resolve all includes
  const contracts = await loadWithBase(sourcePath);

  let content: string;
  if (format === "ts") {
    content = generateTypeScript(contracts);
  } else {
    // Only include base if it was explicitly specified in the contract file
    const jsonData: { base?: string; contracts: typeof contracts.contracts } = {
      contracts: contracts.contracts,
    };
    if (contracts.originalBase !== undefined) {
      jsonData.base = contracts.originalBase;
    }
    content = pretty
      ? JSON.stringify(jsonData, null, 2)
      : JSON.stringify(jsonData);
  }

  // Write output if path provided
  let outputPath: string | undefined;
  if (output) {
    outputPath = output;
    await Deno.writeTextFile(output, content);
  }

  return {
    contracts,
    content,
    json: content, // backwards compatibility
    outputPath,
  };
}

/**
 * Synchronous version of transpile
 */
export function transpileSync(
  sourcePath: string,
  options: TranspileOptions = {}
): TranspileResult {
  const { output, pretty = true, format = "json" } = options;

  // Load and resolve all includes synchronously
  const contracts = loadWithBaseSync(sourcePath);

  let content: string;
  if (format === "ts") {
    content = generateTypeScript(contracts);
  } else {
    // Only include base if it was explicitly specified in the contract file
    const jsonData: { base?: string; contracts: typeof contracts.contracts } = {
      contracts: contracts.contracts,
    };
    if (contracts.originalBase !== undefined) {
      jsonData.base = contracts.originalBase;
    }
    content = pretty
      ? JSON.stringify(jsonData, null, 2)
      : JSON.stringify(jsonData);
  }

  // Write output if path provided
  let outputPath: string | undefined;
  if (output) {
    outputPath = output;
    Deno.writeTextFileSync(output, content);
  }

  return {
    contracts,
    content,
    json: content, // backwards compatibility
    outputPath,
  };
}

/**
 * Generate a default output path based on the source path.
 * Replaces the extension with the specified format extension.
 */
export function getDefaultOutputPath(sourcePath: string, format: "json" | "ts" = "json"): string {
  const ext = sourcePath.split(".").pop();
  if (!ext) return sourcePath + "." + format;
  return sourcePath.slice(0, -ext.length) + format;
}

/**
 * CLI entry point for transpiling contracts.
 *
 * Usage: deno run --allow-read --allow-write transpile.ts [--ts] <source> [output]
 */
if (import.meta.main) {
  const args = [...Deno.args];

  // Check for --ts flag
  let format: "json" | "ts" = "json";
  const tsIndex = args.indexOf("--ts");
  if (tsIndex !== -1) {
    format = "ts";
    args.splice(tsIndex, 1);
  }

  if (args.length < 1) {
    console.error("Usage: deno run --allow-read --allow-write transpile.ts [--ts] <source> [output]");
    console.error("");
    console.error("Options:");
    console.error("  --ts    - Output TypeScript module instead of JSON");
    console.error("");
    console.error("Arguments:");
    console.error("  source  - Path to the source contract file (YAML, TOML, or JSON)");
    console.error("  output  - Optional output path (defaults to source with .json/.ts extension)");
    Deno.exit(1);
  }

  const sourcePath = resolve(args[0]);
  const outputPath = args[1] ? resolve(args[1]) : getDefaultOutputPath(sourcePath, format);

  try {
    const result = await transpile(sourcePath, { output: outputPath, format });
    console.log(`Transpiled ${result.contracts.contracts.length} contracts`);
    console.log(`Format: ${format === "ts" ? "TypeScript" : "JSON"}`);
    console.log(`Output: ${result.outputPath}`);
  } catch (error) {
    console.error("Transpile failed:", (error as Error).message);
    Deno.exit(1);
  }
}
